#!/bin/bash
RECORD_SIZE="1 4 512 1024 4096 8192"
RECORDS_NUM="4000 8000"

for CUR_RECORD_SIZE in $RECORD_SIZE
do
	for CUR_RECORDS_NUM in $RECORDS_NUM
	do
		./record-sorter generate original-data-n$CUR_RECORDS_NUM-s$CUR_RECORD_SIZE $CUR_RECORDS_NUM $CUR_RECORD_SIZE
		./record-sorter copy original-data-n$CUR_RECORDS_NUM-s$CUR_RECORD_SIZE sys-data-n$CUR_RECORDS_NUM-s$CUR_RECORD_SIZE $CUR_RECORDS_NUM $CUR_RECORD_SIZE sys copy original-data-n$CUR_RECORDS_NUM-s$CUR_RECORD_SIZE lib-data-n$CUR_RECORDS_NUM-s$CUR_RECORD_SIZE $CUR_RECORDS_NUM $CUR_RECORD_SIZE lib
		./record-sorter sort sys-data-n$CUR_RECORDS_NUM-s$CUR_RECORD_SIZE $CUR_RECORDS_NUM $CUR_RECORD_SIZE sys sort lib-data-n$CUR_RECORDS_NUM-s$CUR_RECORD_SIZE $CUR_RECORDS_NUM $CUR_RECORD_SIZE lib
	done
done
